<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

     <ItemGroup>
    <!--<PackageReference Include="HangFire" Version="1.6.20" />-->
     <PackageReference Include="NServiceBus" Version="7.1.6" />
    <PackageReference Include="NServiceBus.CustomChecks" Version="3.0.1" />
    <PackageReference Include="NServiceBus.Heartbeat" Version="3.0.1" />
    <PackageReference Include="NServiceBus.Persistence.Sql" Version="4.4.0" />
    <PackageReference Include="NServiceBus.RabbitMQ" Version="5.0.2" />
    <PackageReference Include="NServiceBus.SagaAudit" Version="3.0.1" />
  </ItemGroup>

</Project>
