<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.1.0-preview1-final" />
  </ItemGroup>

  
  <ItemGroup>
    <PackageReference Include="HangFire" Version="1.6.20" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.3" />
    <PackageReference Include="NServiceBus" Version="7.1.6" />
    <PackageReference Include="NServiceBus.CustomChecks" Version="3.0.1" />
    <PackageReference Include="NServiceBus.Heartbeat" Version="3.0.1" />
    <PackageReference Include="NServiceBus.Persistence.Sql" Version="4.4.0" />
    <PackageReference Include="NServiceBus.RabbitMQ" Version="5.0.2" />
    <PackageReference Include="NServiceBus.SagaAudit" Version="3.0.1" />
        <PackageReference Include="NServiceBus.NHibernate" Version="8.1.1" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.3" />
  </ItemGroup>

<ItemGroup>
    <ProjectReference Include="..\Messages\Messages.csproj" />
</ItemGroup>

</Project>
