// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TriagemService.DataContext;

namespace TriagemService.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TriagemService.Data.Models.Operador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NomeOperador")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Operadores");
                });

            modelBuilder.Entity("TriagemService.Data.Models.Triagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCriacao");

                    b.Property<DateTime>("DataExpiracao");

                    b.Property<DateTime>("DataRetirada");

                    b.Property<DateTime>("DataStatus");

                    b.Property<string>("LoteDescarte")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<Guid?>("OperadorId");

                    b.Property<string>("StatusTriagem")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<bool>("Verificada");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId");

                    b.ToTable("Triagens");
                });

            modelBuilder.Entity("TriagemService.Data.Models.Triagem", b =>
                {
                    b.HasOne("TriagemService.Data.Models.Operador", "Operador")
                        .WithMany("Triagem")
                        .HasForeignKey("OperadorId");
                });
#pragma warning restore 612, 618
        }
    }
}
