// <auto-generated />
using DescarteService.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DescarteService.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20190422194355_AddDescarteDBReviews")]
    partial class AddDescarteDBReviews
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DescarteService.Data.Models.ComunicadosDeAgendamentoEnviados", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataEnvioEmail");

                    b.Property<DateTime>("DataPropostaAgendamento");

                    b.Property<Guid>("LoteDescarteId");

                    b.Property<string>("StatusProposta")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("LoteDescarteId");

                    b.ToTable("AgendamentoDescartes");
                });

            modelBuilder.Entity("DescarteService.Data.Models.LoteDescarte", b =>
                {
                    b.Property<Guid>("LoteDescarteId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("EmailResponsavelDescarte")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NomeResponsavelDescarte")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("LoteDescarteId");

                    b.ToTable("LoteDescartes");
                });

            modelBuilder.Entity("DescarteService.Data.Models.ProdutoDescarte", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataVecimentoProduto");

                    b.Property<Guid>("IdITemEstoque");

                    b.Property<Guid>("LoteDescarteId");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<decimal>("QtdeDispUnidade");

                    b.HasKey("Id");

                    b.HasIndex("LoteDescarteId");

                    b.ToTable("ProdutoDescartes");
                });

            modelBuilder.Entity("DescarteService.Data.Models.ComunicadosDeAgendamentoEnviados", b =>
                {
                    b.HasOne("DescarteService.Data.Models.LoteDescarte", "LoteDescarte")
                        .WithMany()
                        .HasForeignKey("LoteDescarteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DescarteService.Data.Models.ProdutoDescarte", b =>
                {
                    b.HasOne("DescarteService.Data.Models.LoteDescarte", "LoteDescarte")
                        .WithMany("ProdutosDescartes")
                        .HasForeignKey("LoteDescarteId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
