// <auto-generated />
using AgendaService.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace AgendaService.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20190210191851_AddAgendaServiceDBReviews")]
    partial class AddAgendaServiceDBReviews
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgendaService.Data.Models.Agenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataAgenda");

                    b.Property<DateTime>("DataCriacao");

                    b.Property<DateTime>("DataExpiracao");

                    b.Property<DateTime>("DataStatus");

                    b.Property<string>("LoteDescarte")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<Guid?>("ResponsavelId");

                    b.Property<string>("StatusAgenda")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<bool>("Verificada");

                    b.HasKey("Id");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("AgendaService.Data.Models.Responsavel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("AgendaService.Data.Models.Agenda", b =>
                {
                    b.HasOne("AgendaService.Data.Models.Responsavel", "Responsavel")
                        .WithMany("Agenda")
                        .HasForeignKey("ResponsavelId");
                });
#pragma warning restore 612, 618
        }
    }
}
