// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using AgendaService.DataContext;

namespace AgendaService.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20190210011838_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgendaService.Data.Models.Operador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("NomeOperador")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.ToTable("Operadores");
                });

            modelBuilder.Entity("AgendaService.Data.Models.Agenda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataCriacao");

                    b.Property<DateTime>("DataExpiracao");

                    b.Property<DateTime>("DataRetirada");

                    b.Property<DateTime>("DataStatus");

                    b.Property<string>("LoteDescarte")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<Guid?>("OperadorId");

                    b.Property<string>("StatusAgenda")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.Property<bool>("Verificada");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("AgendaService.Data.Models.Agenda", b =>
                {
                    b.HasOne("AgendaService.Data.Models.Operador", "Operador")
                        .WithMany("Agenda")
                        .HasForeignKey("OperadorId");
                });
#pragma warning restore 612, 618
        }
    }
}
