// <auto-generated />
using EstoqueService.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EstoqueService.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20181102224443_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EstoqueService.Data.Models.Estoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataInclusao");

                    b.Property<DateTime>("DataVecimentoProduto");

                    b.Property<bool>("Descartado");

                    b.Property<int>("FornecedorId");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("ProdutoId");

                    b.Property<decimal>("QtdeDispUnidade");

                    b.Property<int>("RevendedorId");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("RevendedorId");

                    b.ToTable("Estoques");
                });

            modelBuilder.Entity("EstoqueService.Data.Models.Fornecedor", b =>
                {
                    b.Property<int>("FornecedorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("FornecedorId");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("EstoqueService.Data.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<decimal>("PesoCheio");

                    b.Property<decimal>("PesoVazio");

                    b.Property<decimal>("Valor");

                    b.Property<decimal>("VolumeEmbalagem");

                    b.HasKey("Id");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("EstoqueService.Data.Models.Revendedor", b =>
                {
                    b.Property<int>("RevendedorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("RevendedorId");

                    b.ToTable("Revendedores");
                });

            modelBuilder.Entity("EstoqueService.Data.Models.Estoque", b =>
                {
                    b.HasOne("EstoqueService.Data.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EstoqueService.Data.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("EstoqueService.Data.Models.Revendedor", "Revendedor")
                        .WithMany()
                        .HasForeignKey("RevendedorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
