// <auto-generated />
using EstoqueService.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EstoqueService.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EstoqueService.Data.Models.Estoque", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DataInclusao");

                    b.Property<DateTime>("DataVecimentoProduto");

                    b.Property<bool>("Descartado");

                    b.Property<int?>("FabricanteId");

                    b.Property<string>("Lote")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<Guid?>("ProdutoId");

                    b.Property<decimal>("QtdeDispUnidade");

                    b.Property<int?>("RevendedorId");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(3);

                    b.HasKey("Id");

                    b.HasIndex("FabricanteId");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("RevendedorId");

                    b.ToTable("Estoques");
                });

            modelBuilder.Entity("EstoqueService.Data.Models.Fabricante", b =>
                {
                    b.Property<int>("FabricanteId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("FabricanteId");

                    b.ToTable("Fabricantes");
                });

            modelBuilder.Entity("EstoqueService.Data.Models.Produto", b =>
                {
                    b.Property<Guid>("ProdutoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<decimal>("PesoCheio");

                    b.Property<decimal>("PesoVazio");

                    b.Property<decimal>("Valor");

                    b.Property<decimal>("VolumeEmbalagem");

                    b.HasKey("ProdutoId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("EstoqueService.Data.Models.Revendedor", b =>
                {
                    b.Property<int>("RevendedorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("RevendedorId");

                    b.ToTable("Revendedores");
                });

            modelBuilder.Entity("EstoqueService.Data.Models.Estoque", b =>
                {
                    b.HasOne("EstoqueService.Data.Models.Fabricante", "Fabricante")
                        .WithMany("Estoques")
                        .HasForeignKey("FabricanteId");

                    b.HasOne("EstoqueService.Data.Models.Produto", "Produto")
                        .WithMany("Estoques")
                        .HasForeignKey("ProdutoId");

                    b.HasOne("EstoqueService.Data.Models.Revendedor", "Revendedor")
                        .WithMany("Estoques")
                        .HasForeignKey("RevendedorId");
                });
#pragma warning restore 612, 618
        }
    }
}
